import { SearchBar } from '@/components/SearchBar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Cart } from '@/components/Cart';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <header className="border-b fixed w-full bg-white z-[1000]">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <Link href={'/'}><h1 className="text-2xl font-bold cursor-pointer">Store</h1></Link>
          <div className="flex items-center gap-4 ml-4">
            <SearchBar />
            <Cart />
          </div>
        </div>
      </header>
        {children}</body>
    </html>
  );
}
